data:
  raw_dir: "data/raw/NEU-DET/train/images"
  annotation_dir: "data/raw/NEU-DET/train/annotations"
  processed_dir: "data/processed/neu_det_roi"

image:
  size: 128
  grayscale: true

preprocess:
  use_annotation_roi: true
  roi_margin: 0.08
  enhance_contrast: true
  denoise: true
  min_box_size: 6

augmentation:
  traditional:
    enable: false
  gan:
    enable: true
    epochs: 500          # 建议至少 500 轮
    batch_size: 4        # 如果显存不足，改为 2
    image_size: 128
    latent_dim: 100
    lr: 0.0002
    lr_g: 0.0002
    lr_d: 0.00005
    save_interval: 20
    num_test_samples: 8

evaluation:
  metrics: ["SSIM", "PSNR"]
  visualize: true
  output_dir: "results"
